In [1]:
import pandas as pd
import torch
import util

In [2]:
names = util.get_names()

name count: 6782


In [3]:
chars = ".abcdefghijklmnopqrstuvwxyz"

ctoi = {c:i for i,c in enumerate(chars)}
itoc = {i:c for i,c in enumerate(chars)}

n = len(chars)

print(n)

27


In [133]:
model = torch.ones([n, n], dtype=torch.float32)

print(model[0])

for name in names:
    chars = list('.' + name + '.')
    for a, b in zip(chars, chars[1:]):
        model[ctoi[a]][ctoi[b]] += 1.0

model /= model.sum(dim=1, keepdim=True)

print(model.sum(dim=1, keepdim=True)[0])

print(model[0])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1.0000])
tensor([0.0005, 0.1243, 0.0449, 0.0715, 0.0577, 0.0444, 0.0133, 0.0306, 0.0257,
        0.0183, 0.0992, 0.0804, 0.0553, 0.0863, 0.0257, 0.0069, 0.0212, 0.0039,
        0.0513, 0.0548, 0.0370, 0.0025, 0.0099, 0.0089, 0.0030, 0.0099, 0.0128])


In [147]:
generator = torch.Generator().manual_seed(0)

for i in range(20):
    name = '.'
    while name[-1] != '.' or len(name) == 1:
        last: str = name[-1]
        selection = torch.multinomial(model[ctoi[last]], 1, replacement=True, generator=generator)
        item = selection.item()
        char = itoc[int(item)]
        name += char

    name = name[1:-1]
    print(f"{name}")

kedon
frenakey
aderyn
esalller
riopberqwa
cha
ziale
kanocizaylinalexa
m
cyl
kar
rl
jesho
jqushria
peanzen
k
dyaga
jamisohaynte
deychyl
iod


In [12]:
print("Analyzing the number of 'parameters' that would be necessary to expand the context to include more preceeding letters")
print(f"1: {27**2:,}")
print(f"2: {27**3:,}")
print(f"3: {27**4:,}")
print(f"4: {27**5:,}")
print(f"5: {27**6:,}")
print(f"6: {27**7:,}")
print(f"7: {27**8:,}")
print(f"8: {27**9:,}")

Analyzing the number of 'parameters' that would be necessary to expand the context to include more preceeding letters
1: 729
2: 19,683
3: 531,441
4: 14,348,907
5: 387,420,489
6: 10,460,353,203
7: 282,429,536,481
8: 7,625,597,484,987
